import type { ActivityPlan, PlanVariant, RepAffinity, SalesRep, SalesTarget } from "@/types";

export const mockSalesRep: SalesRep = {
  rep_id: 1,
  rep_name: "山田太郎",
  department_id: 1,
  manager_rep_id: null,
};

export const mockSalesTarget: SalesTarget = {
  rep_id: 1,
  target_month: "2026-08",
  target_amount: 4950000,
  target_deal_count: 4,
};

export const mockActivityPlans: ActivityPlan[] = [
  {
    plan_id: 1,
    rep_id: 1,
    plan_date: "2026-08-24",
    customer_id: 10,
    customer_name: "大東物産",
    deal_id: 101,
    activity_type_id: 1,
    activity_type_name: "訪問",
    priority: 1,
    expected_amount: 950000,
    expected_probability: 60,
    is_ai_generated: true,
    reasoning_text: "過去の製造業向け商談での成約率が高く、優先度を高く設定しました。",
    result_status: "pending",
  },
  {
    plan_id: 2,
    rep_id: 1,
    plan_date: "2026-08-25",
    customer_id: 10,
    customer_name: "大東物産",
    deal_id: 102,
    activity_type_id: 2,
    activity_type_name: "電話",
    priority: 2,
    expected_amount: 480000,
    expected_probability: 45,
    is_ai_generated: true,
    reasoning_text: "前回訪問のフォローアップとして、確度が下がる前の週内連絡を提案しました。",
    result_status: "pending",
  },
  {
    plan_id: 3,
    rep_id: 1,
    plan_date: "2026-08-26",
    customer_id: 11,
    customer_name: "さくら商事",
    deal_id: 103,
    activity_type_id: 3,
    activity_type_name: "メール",
    priority: 3,
    expected_amount: 400000,
    expected_probability: 25,
    is_ai_generated: true,
    reasoning_text: "過去に同規模案件を一度見送りとなっているため、優先度を抑えた軽いタッチでの接点維持を提案しました。",
    result_status: "pending",
  },
  {
    plan_id: 4,
    rep_id: 1,
    plan_date: "2026-08-31",
    customer_id: 13,
    customer_name: "北陸精密",
    deal_id: 105,
    activity_type_id: 1,
    activity_type_name: "訪問",
    priority: 4,
    expected_amount: 610000,
    expected_probability: 35,
    is_ai_generated: true,
    reasoning_text: "月末に向けて活動が手薄になっている週を補うため、新規の商談機会を追加しました。",
    result_status: "pending",
  },
];

// 既存の計画が失注・延期になった際に、AIが代わりに差し込む候補（自動再計画のデモ用）
export const mockReplacementCandidates: ActivityPlan[] = [
  {
    plan_id: 104,
    rep_id: 1,
    plan_date: "2026-08-27",
    customer_id: 12,
    customer_name: "東西システムズ",
    deal_id: 104,
    activity_type_id: 4,
    activity_type_name: "Web会議",
    priority: 2,
    expected_amount: 520000,
    expected_probability: 50,
    is_ai_generated: true,
    reasoning_text: "既存計画の失注・延期を補うため、直近で日程調整しやすいWeb会議で東西システムズへ提案します。",
    result_status: "pending",
  },
];

export const mockPlanVariants: PlanVariant[] = [
  {
    variant_id: "A",
    label: "プランA(バランス型)",
    description: "既存顧客のフォローと新規案件をバランスよく組み合わせた標準プラン",
    plans: mockActivityPlans,
  },
  {
    variant_id: "B",
    label: "プランB(新規開拓重視)",
    description: "新規・見込みの薄い顧客への接点を増やし、パイプラインの幅を広げるプラン",
    plans: [
      {
        plan_id: 201,
        rep_id: 1,
        plan_date: "2026-08-24",
        customer_id: 10,
        customer_name: "大東物産",
        deal_id: 201,
        activity_type_id: 1,
        activity_type_name: "訪問",
        priority: 1,
        expected_amount: 950000,
        expected_probability: 60,
        is_ai_generated: true,
        reasoning_text: "確度の高い既存商談は維持しつつ、他の枠は新規開拓に振り分けました。",
        result_status: "pending",
      },
      {
        plan_id: 202,
        rep_id: 1,
        plan_date: "2026-08-25",
        customer_id: 12,
        customer_name: "東西システムズ",
        deal_id: 202,
        activity_type_id: 4,
        activity_type_name: "Web会議",
        priority: 2,
        expected_amount: 520000,
        expected_probability: 50,
        is_ai_generated: true,
        reasoning_text: "未接触の見込み客のため、まずはWeb会議で関係構築を図ります。",
        result_status: "pending",
      },
      {
        plan_id: 203,
        rep_id: 1,
        plan_date: "2026-08-27",
        customer_id: 13,
        customer_name: "北陸精密",
        deal_id: 203,
        activity_type_id: 1,
        activity_type_name: "訪問",
        priority: 3,
        expected_amount: 610000,
        expected_probability: 40,
        is_ai_generated: true,
        reasoning_text: "月末を待たず早期に接触し、新規開拓の機会損失を防ぎます。",
        result_status: "pending",
      },
      {
        plan_id: 204,
        rep_id: 1,
        plan_date: "2026-08-28",
        customer_id: 11,
        customer_name: "さくら商事",
        deal_id: 204,
        activity_type_id: 3,
        activity_type_name: "メール",
        priority: 4,
        expected_amount: 400000,
        expected_probability: 20,
        is_ai_generated: true,
        reasoning_text: "優先度は下げつつも接点は絶やさない位置づけです。",
        result_status: "pending",
      },
    ],
  },
  {
    variant_id: "C",
    label: "プランC(堅実型)",
    description: "確度の高い商談だけに絞り込み、着実に刈り取ることを優先したプラン",
    plans: [
      {
        plan_id: 301,
        rep_id: 1,
        plan_date: "2026-08-24",
        customer_id: 10,
        customer_name: "大東物産",
        deal_id: 301,
        activity_type_id: 1,
        activity_type_name: "訪問",
        priority: 1,
        expected_amount: 950000,
        expected_probability: 65,
        is_ai_generated: true,
        reasoning_text: "最重要商談に集中し、訪問の質を高めて確度を引き上げます。",
        result_status: "pending",
      },
      {
        plan_id: 302,
        rep_id: 1,
        plan_date: "2026-08-26",
        customer_id: 10,
        customer_name: "大東物産",
        deal_id: 302,
        activity_type_id: 2,
        activity_type_name: "電話",
        priority: 2,
        expected_amount: 480000,
        expected_probability: 55,
        is_ai_generated: true,
        reasoning_text: "追加のフォロー連絡で意思決定を後押しし、確実な成約を狙います。",
        result_status: "pending",
      },
    ],
  },
];

export const mockRepAffinities: RepAffinity[] = [
  { rep_id: 1, category_id: 1, category_name: "製造業", score: 82 },
  { rep_id: 1, category_id: 2, category_name: "卸売業", score: 55 },
  { rep_id: 1, category_id: 3, category_name: "小売業", score: 30 },
];
